---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kisara71.
--- DateTime: 2025/6/12 19:17
---

local key = KEYS[1]

local window = tonumber(ARGV[1])
local threshold = tonumber(ARGV[2])
local now = tonumber(ARGV[3])

local min = now - window

redis.call("ZREMRANGEBYSCORE", key, '-inf', min)

local count = redis.call("ZCOUNT", key, min, '+inf')

if count >= threshold then
    return "true"
else
    redis.call("ZADD", key, now, now)
    redis.call("PEXPIRE", key, window)
    return "false"
end